// default package
// Generated 2021-1-18 22:21:03 by Hibernate Tools 4.0.1.Final
package org.bsm.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Booksimpleinfo generated by hbm2java
 */
@Entity
@Table(name = "booksimpleinfo", catalog = "bookmanager")
public class Booksimpleinfo implements java.io.Serializable {

    private Integer id;
    private String isbn;
    private String name;
    private String title;
    private String author;
    private String introduction;

    public Booksimpleinfo() {
    }

    public Booksimpleinfo(String isbn, String name, String title, String author, String introduction) {
        this.isbn = isbn;
        this.name = name;
        this.title = title;
        this.author = author;
        this.introduction = introduction;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "isbn", length = 32)
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Column(name = "name", length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "title", length = 128)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "author", length = 32)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "introduction", length = 65535)
    public String getIntroduction() {
        return this.introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

}
