package org.bsm.model;
// Generated 2020-1-1 16:12:16 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bookmanager")
public class Book implements java.io.Serializable {

	private String isbn;
	private String id;
	private String name;
	private Double price;
	private Integer remainnumber;

	public Book() {
	}

	public Book(String isbn) {
		this.isbn = isbn;
	}

	public Book(String isbn, String id, String name, Double price, Integer remainnumber) {
		this.isbn = isbn;
		this.id = id;
		this.name = name;
		this.price = price;
		this.remainnumber = remainnumber;
	}

	@Id

	@Column(name = "isbn", unique = true, nullable = false)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "id", length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "remainnumber")
	public Integer getRemainnumber() {
		return this.remainnumber;
	}

	public void setRemainnumber(Integer remainnumber) {
		this.remainnumber = remainnumber;
	}

}
