package org.bsm.model;
// Generated 2020-2-13 22:52:44 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbookId generated by hbm2java
 */
@Embeddable
public class TbookId implements java.io.Serializable {

    private String code;
    private String isbn;

    public TbookId() {
    }

    public TbookId(String code, String isbn) {
        this.code = code;
        this.isbn = isbn;
    }

    @Column(name = "code", nullable = false, length = 32)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "isbn", nullable = false, length = 32)
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TbookId))
            return false;
        TbookId castOther = (TbookId) other;

        return ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
                && this.getCode().equals(castOther.getCode())))
                && ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null && castOther.getIsbn() != null
                && this.getIsbn().equals(castOther.getIsbn())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
        result = 37 * result + (getIsbn() == null ? 0 : this.getIsbn().hashCode());
        return result;
    }

}
