// default package
// Generated 2021-1-18 22:21:03 by Hibernate Tools 4.0.1.Final
package org.bsm.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbookId generated by hbm2java
 */
@Embeddable
public class TbookId implements java.io.Serializable {

	private int id;
	private String code;
	private String isbn;

	public TbookId() {
	}

	public TbookId(int id, String code, String isbn) {
		this.id = id;
		this.code = code;
		this.isbn = isbn;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 32)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "isbn", nullable = false, length = 32)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbookId))
			return false;
		TbookId castOther = (TbookId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& ((this.getIsbn() == castOther.getIsbn()) || (this.getIsbn() != null && castOther.getIsbn() != null
						&& this.getIsbn().equals(castOther.getIsbn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getIsbn() == null ? 0 : this.getIsbn().hashCode());
		return result;
	}

}
