package org.bsm.model;
// Generated 2020-1-30 22:28:22 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trole generated by hbm2java
 */
@Entity
@Table(name = "trole", catalog = "bookmanager")
public class Trole implements java.io.Serializable {

	private Integer roleid;
	private String rolename;
	private String remark;
	private String excol;
	private Set<Tauthorize> tauthorizes = new HashSet<Tauthorize>(0);
	private Set<Tuser> tusers = new HashSet<Tuser>(0);

	public Trole() {
	}

	public Trole(Integer roleid) {
		this.roleid = roleid;
	}

	public Trole(int roleid, String rolename, String remark, String excol, Set<Tauthorize> tauthorizes,
			Set<Tuser> tusers) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.remark = remark;
		this.excol = excol;
		this.tauthorizes = tauthorizes;
		this.tusers = tusers;
	}

	@Id

	@Column(name = "roleid", unique = true, nullable = false)
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	@Column(name = "rolename", length = 36)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "excol", length = 200)
	public String getExcol() {
		return this.excol;
	}

	public void setExcol(String excol) {
		this.excol = excol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trole")
	public Set<Tauthorize> getTauthorizes() {
		return this.tauthorizes;
	}

	public void setTauthorizes(Set<Tauthorize> tauthorizes) {
		this.tauthorizes = tauthorizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trole")
	public Set<Tuser> getTusers() {
		return this.tusers;
	}

	public void setTusers(Set<Tuser> tusers) {
		this.tusers = tusers;
	}

}
