package org.bsm.model;
// Generated 2020-1-14 13:50:33 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name = "tuser", catalog = "bookmanager")
public class Tuser implements java.io.Serializable {

	private String name;
	private String id;
	private String pwd;
	private Date createdatetime;
	private Date lastmodifytime;

	public Tuser() {
	}

	public Tuser(String name, String id) {
		this.name = name;
		this.id = id;
	}

	public Tuser(String name, String id, String pwd, Date createdatetime, Date lastmodifytime) {
		this.name = name;
		this.id = id;
		this.pwd = pwd;
		this.createdatetime = createdatetime;
		this.lastmodifytime = lastmodifytime;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false, length = 36)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id", nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "pwd")
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdatetime", length = 19)
	public Date getCreatedatetime() {
		return this.createdatetime;
	}

	public void setCreatedatetime(Date createdatetime) {
		this.createdatetime = createdatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifytime", length = 19)
	public Date getLastmodifytime() {
		return this.lastmodifytime;
	}

	public void setLastmodifytime(Date lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

}
